#!/usr/bin/env python3
"""
Extract manual-review-required records from Dify export-app-messages output.

Input:
  - .jsonl.gz generated by:
    flask export-app-messages --app-id ... --filename ...

Output:
  - CSV records where review flag is true.
  - Optional POST to queue API endpoint for centralized aggregation.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import json
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from review_common import parse_review_fields


@dataclass
class ReviewRecord:
    message_id: str
    conversation_id: str
    query: str
    audience: str
    need_manual_review: bool
    review_category: str
    confidence: str
    reason: str
    source: str
    ingress: str
    status: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "message_id": self.message_id,
            "conversation_id": self.conversation_id,
            "query": self.query,
            "audience": self.audience,
            "need_manual_review": self.need_manual_review,
            "review_category": self.review_category,
            "confidence": self.confidence,
            "reason": self.reason,
            "source": self.source,
            "ingress": self.ingress,
            "status": self.status,
        }


def iter_jsonl_gz(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with gzip.open(path, mode="rt", encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            content = line.strip()
            if not content:
                continue
            try:
                records.append(json.loads(content))
            except json.JSONDecodeError as error:
                print(f"[WARN] Skip line {line_number}, invalid JSON: {error}", file=sys.stderr)
    return records


def build_review_records(raw_records: list[dict[str, Any]], source: str, ingress: str) -> list[ReviewRecord]:
    deduplicated: dict[str, ReviewRecord] = {}
    for raw_record in raw_records:
        message_id = str(raw_record.get("message_id", "")).strip()
        conversation_id = str(raw_record.get("conversation_id", "")).strip()
        query = str(raw_record.get("query", "")).strip()
        audience = str((raw_record.get("inputs") or {}).get("audience", "")).strip()
        answer = str(raw_record.get("answer", "") or "")
        need_manual_review, category, confidence, reason = parse_review_fields(answer)

        if not need_manual_review:
            continue
        if not message_id:
            continue

        deduplicated[message_id] = ReviewRecord(
            message_id=message_id,
            conversation_id=conversation_id,
            query=query,
            audience=audience,
            need_manual_review=True,
            review_category=category,
            confidence=confidence,
            reason=reason,
            source=source,
            ingress=ingress,
            status="pending",
        )
    return list(deduplicated.values())


def write_csv(path: Path, review_records: list[ReviewRecord]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    headers = [
        "message_id",
        "conversation_id",
        "query",
        "audience",
        "need_manual_review",
        "review_category",
        "confidence",
        "reason",
        "source",
        "ingress",
        "status",
    ]
    with path.open(mode="w", encoding="utf-8-sig", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=headers)
        writer.writeheader()
        for record in review_records:
            writer.writerow(record.to_dict())


def post_records(
    queue_api_url: str,
    queue_api_token: str | None,
    review_records: list[ReviewRecord],
    timeout_seconds: float,
) -> tuple[int, int]:
    success_count = 0
    failed_count = 0

    for review_record in review_records:
        payload = json.dumps(review_record.to_dict()).encode("utf-8")
        headers = {"Content-Type": "application/json"}
        if queue_api_token:
            headers["Authorization"] = f"Bearer {queue_api_token}"

        request = urllib.request.Request(
            url=queue_api_url,
            data=payload,
            headers=headers,
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
                if 200 <= response.status < 300:
                    success_count += 1
                else:
                    failed_count += 1
                    print(
                        f"[WARN] POST failed for message_id={review_record.message_id}, status={response.status}",
                        file=sys.stderr,
                    )
        except urllib.error.URLError as error:
            failed_count += 1
            print(
                f"[WARN] POST failed for message_id={review_record.message_id}, error={error}",
                file=sys.stderr,
            )
    return success_count, failed_count


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Filter manual-review-required records from Dify export jsonl.gz.")
    parser.add_argument("--input", required=True, help="Input .jsonl.gz path generated by export-app-messages")
    parser.add_argument("--output-csv", required=True, help="Output csv path for filtered records")
    parser.add_argument("--source", default="batch_reconcile", help="Record source field")
    parser.add_argument("--ingress", default="export_reconcile", help="Record ingress field")
    parser.add_argument("--queue-api-url", default="", help="Optional queue API URL for POST")
    parser.add_argument("--queue-api-token", default="", help="Optional Bearer token for queue API")
    parser.add_argument("--timeout-seconds", type=float, default=5.0, help="HTTP timeout when posting records")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_path = Path(args.input).expanduser().resolve()
    output_csv_path = Path(args.output_csv).expanduser().resolve()

    if not input_path.exists() or not input_path.is_file():
        print(f"[ERROR] Input file not found: {input_path}", file=sys.stderr)
        return 1

    raw_records = iter_jsonl_gz(input_path)
    review_records = build_review_records(raw_records, source=args.source, ingress=args.ingress)
    write_csv(output_csv_path, review_records)

    print(f"[INFO] Input records: {len(raw_records)}")
    print(f"[INFO] Need manual review records: {len(review_records)}")
    print(f"[INFO] CSV written: {output_csv_path}")

    if args.queue_api_url:
        success_count, failed_count = post_records(
            queue_api_url=args.queue_api_url.strip(),
            queue_api_token=args.queue_api_token.strip() or None,
            review_records=review_records,
            timeout_seconds=args.timeout_seconds,
        )
        print(f"[INFO] Queue POST success: {success_count}, failed: {failed_count}")
        if failed_count > 0:
            return 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
